default_stages: [ "pre-commit", "commit-msg", "pre-push" ]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "License inserter"
        files: \.py$
        args:
          - --license-filepath=license_header.txt
          - --comment-style=#
          - --detect-license-in-X-top-lines=1 
        exclude: (^|.*/)(esm)/.*